/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./../components/background.vue')['default']
    Footer: typeof import('./../components/footer.vue')['default']
    Left: typeof import('./../components/main/left.vue')['default']
    LeftMessage: typeof import('./../components/left-message.vue')['default']
    MainLeft: typeof import('./../components/main-left.vue')['default']
    Message: typeof import('./../components/message.vue')['default']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  }
}
